/-
  LowerBound/SK/SlabCountingRing.lean — Token ring port of SlabCounting (b)

  Connects the abstract slab-counting theorem in `SlabCounting.lean` to the
  `GoodCycle` / `DetDict` infrastructure via α/β counting.

  §6 obligations from the ship plan:
    (a) slabSize ≥ 2^(n-3)            — Step 4
    (b) ∑ blocked ≤ (n+1)·L            — Step 2 (THIS FILE)
        via Σα = L (Step 2b) + Σβ ≤ n·L (Step 2c)
    (c) unblocked entry ⟹ VC-NG edge  — Step 5
    (d) wire the chain lemma            — Step 6 (uses bridge)

  Session 2a deliverable: scaffolding + aggregated theorem signature.
  Body left as `sorry`; sub-lemmas emerge in 2b/2c.
-/
import LeanMn.LowerBound.SK.SlabCounting
import LeanMn.LowerBound.SK.Forcing
import LeanMn.LowerBound.GoodCycleBasics

namespace LeanMn.SK

open scoped BigOperators

variable {sys : System}

/-- A move entry in the determined dictionary of a good cycle:
    key `(i, l, s, r)` with forced output `v ≠ s`. -/
structure MoveEntry (sys : System) (gc : GoodCycle sys) where
  i : Fin sys.rs.n
  l : Fin (sys.rs.m (left i))
  s : Fin (sys.rs.m i)
  r : Fin (sys.rs.m (right i))
  v : Fin (sys.rs.m i)
  /-- The det has this entry. -/
  in_det : detOf gc i l s r = some v
  /-- The entry is a move, not a stay. -/
  is_move : v ≠ s

namespace MoveEntry

variable {gc : GoodCycle sys}

/-- α count: cycle configs whose local triple at position `i` matches
    the SOURCE triple `(l, s, r)` of this entry.

    Structural claim (Step 2b, `sum_alpha_eq_L`): in a fair simple cycle,
    Σ α over all move entries = L exactly. Each entry has α = 1 (the
    unique firing config with that source triple). -/
noncomputable def alpha (e : MoveEntry sys gc) : ℕ :=
  (gc.configs.filter (fun c =>
    c (left e.i) = e.l ∧ c e.i = e.s ∧ c (right e.i) = e.r)).length

/-- β count: cycle configs whose local triple at position `i` matches
    the TARGET triple `(l, v, r)` of this entry.

    Structural claim (Step 2c, `sum_beta_le_n_mul_L`): Σ β over all
    move entries ≤ n · L. Each cycle config can be the target triple
    at each of the n positions at most once, so each contributes ≤ n. -/
noncomputable def beta (e : MoveEntry sys gc) : ℕ :=
  (gc.configs.filter (fun c =>
    c (left e.i) = e.l ∧ c e.i = e.v ∧ c (right e.i) = e.r)).length

/-- Slab size: product of `|V_j|` over positions `j` NOT in the
    neighborhood `{left i, i, right i}` of this entry.

    Since each `|V_j| ≥ 2` (fairness, Step 4 obligation), this is
    `≥ 2^(n-3)`. -/
noncomputable def slabSize (e : MoveEntry sys gc) : ℕ :=
  (Finset.univ.filter
    (fun j : Fin sys.rs.n => j ≠ left e.i ∧ j ≠ e.i ∧ j ≠ right e.i)).prod
    (fun j => sys.rs.m j)

/-- Blocking budget for an entry: α + β. An entry is *blocked* iff
    `blocked ≥ slabSize`. Slab-counting shows not all entries can be
    blocked when `slabSize > n + 1`. -/
noncomputable def blocked (e : MoveEntry sys gc) : ℕ :=
  e.alpha + e.beta

end MoveEntry

/-! ## Step-indexed move entry

For each step `k : Fin gc.configs.length` of a good cycle, the
configuration at step `k` fires at `gc.moverAt k`. This produces a
canonical `MoveEntry` whose source triple is the local triple at the
mover's position, and whose forced output is the next configuration's
value at that position.

These step-indexed entries are the workhorses for the `Σα = L` and
`Σβ ≤ n·L` aggregations in Sessions 2b/2c. -/

/-- The move entry generated by firing step `k` of the good cycle.

The four source fields are the local context of the mover at step `k`;
the forced output `v` is the cycle's next value at the mover's position,
equivalently `sys.f i l s r`. -/
noncomputable def stepMoveEntry (gc : GoodCycle sys) (k : Fin gc.configs.length) :
    MoveEntry sys gc :=
  { i := gc.moverAt k
    l := (gc.configs.get k) (left (gc.moverAt k))
    s := (gc.configs.get k) (gc.moverAt k)
    r := (gc.configs.get k) (right (gc.moverAt k))
    v := sys.f (gc.moverAt k)
          ((gc.configs.get k) (left (gc.moverAt k)))
          ((gc.configs.get k) (gc.moverAt k))
          ((gc.configs.get k) (right (gc.moverAt k)))
    in_det := by
      -- `detOf` finds the first step k' whose local triple at the
      -- mover's position matches the triple of step k; we show the
      -- next-config value at that step equals `sys.f i l s r`.
      simp only [detOf]
      -- Step k itself satisfies the find? predicate.
      generalize hfind :
        (List.finRange gc.configs.length).find?
          (fun k' =>
            (gc.configs.get k' (left (gc.moverAt k)) ==
              (gc.configs.get k) (left (gc.moverAt k))) &&
            (gc.configs.get k' (gc.moverAt k) ==
              (gc.configs.get k) (gc.moverAt k)) &&
            (gc.configs.get k' (right (gc.moverAt k)) ==
              (gc.configs.get k) (right (gc.moverAt k)))) = found
      cases found with
      | none =>
        -- Impossible: step k satisfies the predicate.
        exfalso
        have hk_pred :
            (fun k' : Fin gc.configs.length =>
              (gc.configs.get k' (left (gc.moverAt k)) ==
                (gc.configs.get k) (left (gc.moverAt k))) &&
              (gc.configs.get k' (gc.moverAt k) ==
                (gc.configs.get k) (gc.moverAt k)) &&
              (gc.configs.get k' (right (gc.moverAt k)) ==
                (gc.configs.get k) (right (gc.moverAt k)))) k = true := by
          simp
        -- `find? = none` means nothing in the list satisfies the predicate.
        have hforall := List.find?_eq_none.mp hfind
        exact absurd hk_pred (by simpa using hforall k (List.mem_finRange k))
      | some k_found =>
        -- find? gave k_found with matching triple. At k_found, the triple
        -- at position `moverAt k` equals the triple at step k.
        have hmatch := List.find?_some hfind
        simp [Bool.and_eq_true, beq_iff_eq] at hmatch
        obtain ⟨⟨hl, hs⟩, hr⟩ := hmatch
        -- At k_found, `moverAt k` is privileged (triple matches step k's
        -- privileged triple → sys.f ≠ s).
        simp only [← List.get_eq_getElem] at hl hs hr
        have hpriv_f : privileged sys (gc.configs.get k_found) (gc.moverAt k) := by
          have hkprv := gc.moverAt_privileged k
          simp only [privileged] at hkprv ⊢
          rw [hl, hs, hr]
          exact hkprv
        -- Hence moverAt k_found = moverAt k (uniqueness).
        have hmov_eq : gc.moverAt k = gc.moverAt k_found :=
          gc.moverAt_unique k_found (gc.moverAt k) hpriv_f
        -- The step_eq_move at k_found then pins the next value.
        have hstep := gc.step_eq_move k_found
        show some (gc.configs.get (nextIndex gc.configs k_found) (gc.moverAt k)) = some _
        congr 1
        rw [hstep, ← hmov_eq]
        simp only [move, dite_true, Fin.cast_eq_self]
        rw [hl, hs, hr]
    is_move := by
      -- `is_move` is `v ≠ s`, which is exactly `privileged` at the
      -- mover's position.
      exact gc.moverAt_privileged k }

/-- At each firing step, the mover's value changes (`v ≠ s`). Stated
    directly for convenient access. -/
theorem stepMoveEntry_v_ne_s (gc : GoodCycle sys) (k : Fin gc.configs.length) :
    (stepMoveEntry gc k).v ≠ (stepMoveEntry gc k).s :=
  (stepMoveEntry gc k).is_move

/-- The next configuration's value at the mover's position equals the
    entry's forced output `v`. Follows from `step_eq_move`. -/
theorem stepMoveEntry_next_val (gc : GoodCycle sys) (k : Fin gc.configs.length) :
    (gc.configs.get (nextIndex gc.configs k)) (gc.moverAt k) =
      (stepMoveEntry gc k).v := by
  simp only [stepMoveEntry]
  rw [gc.step_eq_move k]
  simp only [move, dite_true]
  rfl

/-! ## Session 2b target: `Σα = L`

We index the α-sum by **distinct source triples** (a dependent Sigma
type `SourceTriple`). The deduplicated Finset `cycleTriples` collects
every (position, local-triple) pair generated by a firing step.

Then `Σ_{t ∈ cycleTriples} α(t) = L` is provable by double-counting:
each cycle config `c` matches exactly one `t ∈ cycleTriples`, namely
`⟨i_c, c's triple at i_c⟩` where `i_c = moverAt` of `c`'s own firing
step. The uniqueness uses `gc.unique_privileged` at `c`: if `c` matches
any `t = ⟨i', τ'⟩ ∈ cycleTriples`, then `i'` is privileged at `c`
(firing condition on the triple) and by uniqueness, `i' = i_c`.
-/

/-- A (position, local-triple) pair. -/
abbrev SourceTriple (sys : System) : Type :=
  Σ i : Fin sys.rs.n,
    Fin (sys.rs.m (left i)) × Fin (sys.rs.m i) × Fin (sys.rs.m (right i))

/-- The source triple generated by firing step `k`. -/
noncomputable def sourceTripleOfStep (gc : GoodCycle sys)
    (k : Fin gc.configs.length) : SourceTriple sys :=
  ⟨gc.moverAt k,
    ((gc.configs.get k) (left (gc.moverAt k)),
     (gc.configs.get k) (gc.moverAt k),
     (gc.configs.get k) (right (gc.moverAt k)))⟩

/-- A config's local triple at a position `i`. -/
def configTripleAt (c : Config sys.rs) (i : Fin sys.rs.n) :
    Fin (sys.rs.m (left i)) × Fin (sys.rs.m i) × Fin (sys.rs.m (right i)) :=
  (c (left i), c i, c (right i))

/-- The (deduplicated) set of source triples produced by all firing
    steps of the cycle. -/
noncomputable def cycleTriples (gc : GoodCycle sys) : Finset (SourceTriple sys) :=
  Finset.image (sourceTripleOfStep gc) Finset.univ

/-- α-count per source triple: the number of cycle configs whose local
    triple at `t.1` equals `t.2`. -/
noncomputable def alphaOfTriple (gc : GoodCycle sys) (t : SourceTriple sys) : ℕ :=
  (gc.configs.filter (fun c => configTripleAt c t.1 = t.2)).length

/-- A cycle config `c` with local triple at position `i'` matching `τ'`
    forces `i'` to be the unique mover at `c`: the triple match
    witnesses that `sys.f i' τ' ≠ τ'.middle = c(i')`. -/
private theorem moverAt_of_match (gc : GoodCycle sys)
    (k : Fin gc.configs.length) (j : Fin gc.configs.length)
    (hmatch : configTripleAt (gc.configs.get k) (gc.moverAt j) =
              configTripleAt (gc.configs.get j) (gc.moverAt j)) :
    gc.moverAt k = gc.moverAt j := by
  -- The triple of c_j at moverAt j is privileged at c_j; matching
  -- triples transfers the privileged predicate to c_k.
  have hpj : privileged sys (gc.configs.get j) (gc.moverAt j) :=
    gc.moverAt_privileged j
  have hpk : privileged sys (gc.configs.get k) (gc.moverAt j) := by
    simp only [privileged, configTripleAt, Prod.mk.injEq] at hmatch ⊢
    obtain ⟨hl, hs, hr⟩ := hmatch
    rw [hl, hs, hr]; exact hpj
  exact (gc.moverAt_unique k (gc.moverAt j) hpk).symm

/-- Each cycle config matches exactly one source triple in
    `cycleTriples`, namely the one generated by its own firing step. -/
private theorem filter_cycleTriples_eq_singleton
    (gc : GoodCycle sys) (k : Fin gc.configs.length) :
    (cycleTriples gc).filter
        (fun t => configTripleAt (gc.configs.get k) t.1 = t.2) =
      {sourceTripleOfStep gc k} := by
  classical
  ext t
  simp only [Finset.mem_filter, Finset.mem_singleton, cycleTriples,
    Finset.mem_image, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨⟨j, rfl⟩, hmatch⟩
    -- `t = sourceTripleOfStep j` and c_k matches t at position moverAt j.
    have hmatch' : configTripleAt (gc.configs.get k) (gc.moverAt j) =
                   configTripleAt (gc.configs.get j) (gc.moverAt j) := by
      simpa [sourceTripleOfStep, configTripleAt] using hmatch
    have hmov : gc.moverAt k = gc.moverAt j :=
      moverAt_of_match gc k j hmatch'
    -- Goal: sourceTripleOfStep gc j = sourceTripleOfStep gc k
    -- Rewrite to unify the first components, then reduce to triple equality.
    show sourceTripleOfStep gc j = sourceTripleOfStep gc k
    unfold sourceTripleOfStep
    rw [hmov]
    -- Now both Sigmas have first component `gc.moverAt j`.
    refine Sigma.ext rfl ?_
    rw [heq_eq_eq]
    -- Goal reduces to triple equality, from hmatch'.symm via configTripleAt.
    simp only [configTripleAt, Prod.mk.injEq] at hmatch'
    obtain ⟨hl, hs, hr⟩ := hmatch'
    rw [hl, hs, hr]
  · rintro rfl
    refine ⟨⟨k, rfl⟩, ?_⟩
    simp [sourceTripleOfStep, configTripleAt]

/-- **Session 2b target**: the sum of α-counts over distinct source
    triples equals the cycle length `L`.

    Formal version of the paper claim `Σα = L`. Proven by reversing the
    double sum: each cycle config contributes to exactly one triple's
    α-count (namely the triple generated by its own firing step), so
    the total equals `|gc.configs| = L`. -/
theorem sum_alpha_eq_L (gc : GoodCycle sys) :
    ∑ t ∈ cycleTriples gc, alphaOfTriple gc t = gc.configs.length := by
  classical
  -- Derive Nodup from gc.distinct (injectivity of get).
  have hnd : gc.configs.Nodup :=
    List.nodup_iff_injective_get.mpr (fun j₁ j₂ h => gc.distinct j₁ j₂ h)
  set C : Finset (Config sys.rs) := gc.configs.toFinset with hC_def
  have hC_card : C.card = gc.configs.length := by
    rw [hC_def]; exact List.toFinset_card_of_nodup hnd
  -- Rewrite each α(t) as a Finset card over C.
  have h_alpha_card : ∀ t : SourceTriple sys, alphaOfTriple gc t =
      (C.filter (fun c => configTripleAt c t.1 = t.2)).card := by
    intro t
    unfold alphaOfTriple
    have heq :
        C.filter (fun c => configTripleAt c t.1 = t.2) =
          (gc.configs.filter
              (fun c => decide (configTripleAt c t.1 = t.2))).toFinset := by
      ext a
      simp [hC_def]
    rw [heq, List.toFinset_card_of_nodup (hnd.filter _)]
  -- Now double-count via sum_comm.
  calc ∑ t ∈ cycleTriples gc, alphaOfTriple gc t
      = ∑ t ∈ cycleTriples gc,
          (C.filter (fun c => configTripleAt c t.1 = t.2)).card :=
        Finset.sum_congr rfl (fun t _ => h_alpha_card t)
    _ = ∑ t ∈ cycleTriples gc, ∑ c ∈ C,
          (if configTripleAt c t.1 = t.2 then 1 else 0 : ℕ) := by
        refine Finset.sum_congr rfl (fun t _ => ?_)
        rw [Finset.card_filter]
    _ = ∑ c ∈ C, ∑ t ∈ cycleTriples gc,
          (if configTripleAt c t.1 = t.2 then 1 else 0 : ℕ) :=
        Finset.sum_comm
    _ = ∑ c ∈ C, ((cycleTriples gc).filter
                    (fun t => configTripleAt c t.1 = t.2)).card := by
        refine Finset.sum_congr rfl (fun c _ => ?_)
        rw [Finset.card_filter]
    _ = ∑ _c ∈ C, (1 : ℕ) := by
        refine Finset.sum_congr rfl (fun c hc => ?_)
        rw [hC_def] at hc
        rw [List.mem_toFinset, List.mem_iff_get] at hc
        obtain ⟨k, hk⟩ := hc
        rw [← hk, filter_cycleTriples_eq_singleton gc k, Finset.card_singleton]
    _ = C.card := by rw [Finset.sum_const, smul_eq_mul, Nat.mul_one]
    _ = gc.configs.length := hC_card

/-! ## Session 2c target: `Σβ ≤ n·L`

Analogously to the α-side, we index β by **distinct target triples**
(position + target local-triple). For each firing step, the target
triple at the mover's position is `(l, f(l,s,r), r)`.

Then `Σ_{u ∈ cycleTargetTriples} β(u) ≤ n · L` is provable by double
counting: each cycle config `c` matches AT MOST ONE target triple
per position (since `c`'s triple at `p` is fixed once `c` and `p` are
chosen), so `#target-triples matching c ≤ n` for every `c`. -/

/-- The target triple generated by firing step `k`: same position as
    `sourceTripleOfStep`, but with the forced output in the middle. -/
noncomputable def targetTripleOfStep (gc : GoodCycle sys)
    (k : Fin gc.configs.length) : SourceTriple sys :=
  ⟨gc.moverAt k,
    ((gc.configs.get k) (left (gc.moverAt k)),
     sys.f (gc.moverAt k)
       ((gc.configs.get k) (left (gc.moverAt k)))
       ((gc.configs.get k) (gc.moverAt k))
       ((gc.configs.get k) (right (gc.moverAt k))),
     (gc.configs.get k) (right (gc.moverAt k)))⟩

/-- The (deduplicated) set of target triples produced by all firing
    steps of the cycle. -/
noncomputable def cycleTargetTriples (gc : GoodCycle sys) :
    Finset (SourceTriple sys) :=
  Finset.image (targetTripleOfStep gc) Finset.univ

/-- β-count per target triple: the number of cycle configs whose local
    triple at `u.1` equals `u.2`. -/
noncomputable def betaOfTarget (gc : GoodCycle sys)
    (u : SourceTriple sys) : ℕ :=
  (gc.configs.filter (fun c => configTripleAt c u.1 = u.2)).length

/-- For each cycle config `c`, the set of distinct target triples it
    matches has cardinality ≤ n: the map `u ↦ u.1` is injective on the
    filtered set, since `u.2 = configTripleAt c u.1` is determined by
    `c` and `u.1`. -/
private theorem filter_cycleTargetTriples_card_le
    (gc : GoodCycle sys) (c : Config sys.rs) :
    ((cycleTargetTriples gc).filter
        (fun u => configTripleAt c u.1 = u.2)).card ≤ sys.rs.n := by
  classical
  -- Every matching target triple u equals ⟨u.1, configTripleAt c u.1⟩.
  have h_sub :
      (cycleTargetTriples gc).filter (fun u => configTripleAt c u.1 = u.2)
        ⊆ (Finset.univ : Finset (Fin sys.rs.n)).image
            (fun p => (⟨p, configTripleAt c p⟩ : SourceTriple sys)) := by
    intro u hu
    simp only [Finset.mem_filter] at hu
    obtain ⟨_, hmatch⟩ := hu
    refine Finset.mem_image.mpr ⟨u.1, Finset.mem_univ _, ?_⟩
    -- Goal: ⟨u.1, configTripleAt c u.1⟩ = u
    rw [hmatch]
  calc ((cycleTargetTriples gc).filter
            (fun u => configTripleAt c u.1 = u.2)).card
      ≤ ((Finset.univ : Finset (Fin sys.rs.n)).image
            (fun p => (⟨p, configTripleAt c p⟩ : SourceTriple sys))).card :=
          Finset.card_le_card h_sub
    _ ≤ (Finset.univ : Finset (Fin sys.rs.n)).card :=
          Finset.card_image_le
    _ = sys.rs.n := by simp

/-- **Session 2c target**: the sum of β-counts over distinct target
    triples is at most `n · L`.

    Formal version of the paper claim `Σβ ≤ n·L`. Proven by reversing
    the double sum: each cycle config matches at most one target triple
    per position, and there are only `n` positions. -/
theorem sum_beta_target_le_n_mul_L (gc : GoodCycle sys) :
    ∑ u ∈ cycleTargetTriples gc, betaOfTarget gc u ≤
      sys.rs.n * gc.configs.length := by
  classical
  have hnd : gc.configs.Nodup :=
    List.nodup_iff_injective_get.mpr (fun j₁ j₂ h => gc.distinct j₁ j₂ h)
  set C : Finset (Config sys.rs) := gc.configs.toFinset with hC_def
  have hC_card : C.card = gc.configs.length := by
    rw [hC_def]; exact List.toFinset_card_of_nodup hnd
  -- Rewrite each β(u) as a Finset card over C.
  have h_beta_card : ∀ u : SourceTriple sys, betaOfTarget gc u =
      (C.filter (fun c => configTripleAt c u.1 = u.2)).card := by
    intro u
    unfold betaOfTarget
    have heq :
        C.filter (fun c => configTripleAt c u.1 = u.2) =
          (gc.configs.filter
              (fun c => decide (configTripleAt c u.1 = u.2))).toFinset := by
      ext a
      simp [hC_def]
    rw [heq, List.toFinset_card_of_nodup (hnd.filter _)]
  -- Double-count via sum_comm, then use the per-config bound.
  calc ∑ u ∈ cycleTargetTriples gc, betaOfTarget gc u
      = ∑ u ∈ cycleTargetTriples gc,
          (C.filter (fun c => configTripleAt c u.1 = u.2)).card :=
        Finset.sum_congr rfl (fun u _ => h_beta_card u)
    _ = ∑ u ∈ cycleTargetTriples gc, ∑ c ∈ C,
          (if configTripleAt c u.1 = u.2 then 1 else 0 : ℕ) := by
        refine Finset.sum_congr rfl (fun u _ => ?_)
        rw [Finset.card_filter]
    _ = ∑ c ∈ C, ∑ u ∈ cycleTargetTriples gc,
          (if configTripleAt c u.1 = u.2 then 1 else 0 : ℕ) :=
        Finset.sum_comm
    _ = ∑ c ∈ C, ((cycleTargetTriples gc).filter
                    (fun u => configTripleAt c u.1 = u.2)).card := by
        refine Finset.sum_congr rfl (fun c _ => ?_)
        rw [Finset.card_filter]
    _ ≤ ∑ _c ∈ C, sys.rs.n :=
        Finset.sum_le_sum
          (fun c _ => filter_cycleTargetTriples_card_le gc c)
    _ = C.card * sys.rs.n := by rw [Finset.sum_const, smul_eq_mul]
    _ = sys.rs.n * gc.configs.length := by rw [hC_card, Nat.mul_comm]

/-! ## §6(b) aggregated target — fiber-budget route

The ship-plan target for Step 2: produce an *unblocked* move entry,
under the sub-threshold product hypothesis and `n ≥ 8`. We index the
blocked sum by MoveEntries (via `stepMoveEntry`) rather than by source
or target triples. The resulting sum is bounded via:

  · α-side: `α(stepMoveEntry k) = 1` for every `k` (source-injectivity
    of the step map — private lemma below, load-bearing sorry).
  · β-side: fiber-budget double-count
    `Σ_k β(targetTripleOfStep k) ≤ L · Σ_p (m_p - 1)`.

Combining with `slabSize ≥ 2^(n-3)`:

  `L + L · Σ(m_p - 1) ≥ L · 2^(n-3)` if all blocked,
  ⇒ `Σ m_p ≥ 2^(n-3) + n - 1`.

The arithmetic lemma `Σ m_p < 2^(n-3) + n - 1` under `Π m < 4·3^(n-2)`
and `n ≥ 8` closes out the contradiction.
-/

/-! ### Source-triple injectivity of `stepMoveEntry`

The step map `k ↦ sourceTripleOfStep gc k` is injective on `Fin L`.
Called out in `sk_primer.md` §7.5 and `sk_fiber_budget_scope_2026-04-19.md`
§1 as "zero-sorry" and load-bearing for `α(stepMoveEntry k) = 1` and
the fiber-budget double-count. A complete Lean proof awaits an
orbit-level argument. Empirical status: zero counter-examples across
n=5..9 in 1190 cycles (probe_sk_L_over_Lstar_2026-04-18.py).
-/

/-- **(SORRY, load-bearing)** Distinct cycle steps have distinct
    **target** triples. Stronger than source-injectivity in general
    (target involves the image under `sys.f`), but mathematically it's
    the morally correct formulation for the fiber-budget: distinct
    firing steps produce distinct post-move triples because the
    determined dictionary `detOf` is a function (entries key uniquely).

    See `docs/lean_docs/sk/sk_a1_conception_log.md` — Strategy
    Register + Mechanism sketch v2 — and
    `notes/memory/project_sk_campaign_active_a1prime_2026-04-20.md`.

    This is the new proof target for the A1' campaign; the previous
    `sourceTripleOfStep_injective` sorry is now reduced to this one via
    `sys.f` functional congruence (below). -/
private theorem targetTripleOfStep_injective (gc : GoodCycle sys) :
    Function.Injective (targetTripleOfStep gc) := by
  sorry

/-- Distinct cycle steps have distinct source triples. Reduced to
    `targetTripleOfStep_injective` via the observation that both
    triples share the same first component (`moverAt k`) and the
    outer `(l, r)` coords; the middle of the target is `sys.f` applied
    to the source coords, so equal source triples force equal target
    triples by functional congruence. -/
private theorem sourceTripleOfStep_injective (gc : GoodCycle sys) :
    Function.Injective (sourceTripleOfStep gc) := by
  intro k k' hsrc
  apply targetTripleOfStep_injective gc
  -- Extract mover equality from the Sigma first component.
  have hmov : gc.moverAt k = gc.moverAt k' := by
    have := congr_arg Sigma.fst hsrc
    simpa [sourceTripleOfStep] using this
  -- Extract (l, s, r) equalities from the Sigma second component.
  -- Use the dependent-Sigma pattern from filter_cycleTriples_eq_singleton.
  show targetTripleOfStep gc k = targetTripleOfStep gc k'
  unfold targetTripleOfStep
  -- Align first components via hmov.
  rw [hmov]
  refine Sigma.ext rfl ?_
  rw [heq_eq_eq]
  -- Extract the triple equality from hsrc after rewriting.
  have hsrc' : sourceTripleOfStep gc k = sourceTripleOfStep gc k' := hsrc
  unfold sourceTripleOfStep at hsrc'
  -- Rewrite the first component of hsrc' to match via hmov.
  rw [hmov] at hsrc'
  -- Now hsrc' : ⟨moverAt k', (l_k, s_k, r_k)⟩ = ⟨moverAt k', (l_k', s_k', r_k')⟩
  -- (with the left Sigma's coords reindexed by hmov). Extract triple eq.
  have htriple := (Sigma.mk.inj_iff.mp hsrc').2
  rw [heq_eq_eq] at htriple
  simp only [Prod.mk.injEq] at htriple
  obtain ⟨hl, hs, hr⟩ := htriple
  -- Goal is now the target triple second components equal (under rw hmov):
  -- (l_k, sys.f (moverAt k') l_k s_k r_k, r_k) = (l_k', sys.f (moverAt k') l_k' s_k' r_k', r_k')
  rw [Prod.mk.injEq, Prod.mk.injEq]
  refine ⟨hl, ?_, hr⟩
  -- sys.f is a function, so equal arguments give equal outputs.
  rw [hl, hs, hr]

/-- Weak form of source-injectivity consumed below: steps with the same
    mover and matching triple-at-mover are equal. -/
private theorem step_eq_of_moverAt_and_triple
    (gc : GoodCycle sys) (k k' : Fin gc.configs.length)
    (hmov : gc.moverAt k' = gc.moverAt k)
    (hl : (gc.configs.get k') (left (gc.moverAt k)) =
          (gc.configs.get k) (left (gc.moverAt k)))
    (hs : (gc.configs.get k') (gc.moverAt k) =
          (gc.configs.get k) (gc.moverAt k))
    (hr : (gc.configs.get k') (right (gc.moverAt k)) =
          (gc.configs.get k) (right (gc.moverAt k))) :
    k' = k := by
  have hsrc : sourceTripleOfStep gc k' = sourceTripleOfStep gc k := by
    unfold sourceTripleOfStep
    rw [hmov]
    refine Sigma.ext rfl ?_
    rw [heq_eq_eq, Prod.mk.injEq, Prod.mk.injEq]
    exact ⟨hl, hs, hr⟩
  exact sourceTripleOfStep_injective gc hsrc

/-- α of `stepMoveEntry gc k` equals 1: only `gc.configs.get k` itself
    matches the source triple at position `moverAt k`. -/
private theorem alpha_stepMoveEntry_eq_one
    (gc : GoodCycle sys) (k : Fin gc.configs.length) :
    (stepMoveEntry gc k).alpha = 1 := by
  classical
  have hnd : gc.configs.Nodup :=
    List.nodup_iff_injective_get.mpr (fun j₁ j₂ h => gc.distinct j₁ j₂ h)
  -- `alpha` unfolds to a filter length over `gc.configs`.
  show (gc.configs.filter (fun c =>
      c (left (gc.moverAt k)) = (gc.configs.get k) (left (gc.moverAt k)) ∧
      c (gc.moverAt k) = (gc.configs.get k) (gc.moverAt k) ∧
      c (right (gc.moverAt k)) =
        (gc.configs.get k) (right (gc.moverAt k)))).length = 1
  -- Convert list-length to Finset-card via Nodup.
  rw [show (gc.configs.filter (fun c =>
      c (left (gc.moverAt k)) = (gc.configs.get k) (left (gc.moverAt k)) ∧
      c (gc.moverAt k) = (gc.configs.get k) (gc.moverAt k) ∧
      c (right (gc.moverAt k)) =
        (gc.configs.get k) (right (gc.moverAt k)))).length =
      (gc.configs.filter (fun c =>
        decide (c (left (gc.moverAt k)) =
                  (gc.configs.get k) (left (gc.moverAt k)) ∧
                c (gc.moverAt k) = (gc.configs.get k) (gc.moverAt k) ∧
                c (right (gc.moverAt k)) =
                  (gc.configs.get k) (right (gc.moverAt k))))).toFinset.card
      by rw [List.toFinset_card_of_nodup (hnd.filter _)]]
  -- Show the filter toFinset equals {gc.configs.get k}.
  suffices h : (gc.configs.filter (fun c =>
      decide (c (left (gc.moverAt k)) =
                (gc.configs.get k) (left (gc.moverAt k)) ∧
              c (gc.moverAt k) = (gc.configs.get k) (gc.moverAt k) ∧
              c (right (gc.moverAt k)) =
                (gc.configs.get k) (right (gc.moverAt k))))).toFinset =
    ({gc.configs.get k} : Finset (Config sys.rs)) by
    rw [h, Finset.card_singleton]
  ext c
  simp only [List.mem_toFinset, List.mem_filter, decide_eq_true_eq,
             Finset.mem_singleton]
  refine ⟨?_, ?_⟩
  · rintro ⟨hmem, hl, hs, hr⟩
    rw [List.mem_iff_get] at hmem
    obtain ⟨k', rfl⟩ := hmem
    have hmatch : configTripleAt (gc.configs.get k') (gc.moverAt k) =
                   configTripleAt (gc.configs.get k) (gc.moverAt k) := by
      simp only [configTripleAt, Prod.mk.injEq]
      exact ⟨hl, hs, hr⟩
    have hmov : gc.moverAt k' = gc.moverAt k :=
      moverAt_of_match gc k' k hmatch
    have : k' = k := step_eq_of_moverAt_and_triple gc k k' hmov hl hs hr
    rw [this]
  · rintro rfl
    exact ⟨List.get_mem _ _, rfl, rfl, rfl⟩

/-! ### Fiber-budget double-count: Σ_k β(target_k) ≤ L · Σ(m_p - 1)

For fixed cycle config `c` and position `p`, the steps `k` with
`moverAt k = p` matching `c` at the target triple are bounded by the
count of preimages of `c(p)` under `sys.f p (c(left p)) - (c(right p))`
minus the identity stay, i.e. `m_p - 1`. Injectivity of `k ↦ c_k(p)`
on this set uses `sourceTripleOfStep_injective`.
-/

/-- For fixed cycle config `c` and position `p`, the steps matching
    `c` at the target triple with mover = `p` are at most `m p - 1`. -/
private theorem matching_steps_card_le
    (gc : GoodCycle sys) (c : Config sys.rs) (p : Fin sys.rs.n) :
    ((Finset.univ : Finset (Fin gc.configs.length)).filter
        (fun k => gc.moverAt k = p ∧
                  (gc.configs.get k) (left p) = c (left p) ∧
                  sys.f p ((gc.configs.get k) (left p))
                    ((gc.configs.get k) p)
                    ((gc.configs.get k) (right p)) = c p ∧
                  (gc.configs.get k) (right p) = c (right p))).card
      ≤ sys.rs.m p - 1 := by
  classical
  set S : Finset (Fin gc.configs.length) :=
    (Finset.univ : Finset (Fin gc.configs.length)).filter
      (fun k => gc.moverAt k = p ∧
                (gc.configs.get k) (left p) = c (left p) ∧
                sys.f p ((gc.configs.get k) (left p))
                  ((gc.configs.get k) p)
                  ((gc.configs.get k) (right p)) = c p ∧
                (gc.configs.get k) (right p) = c (right p))
    with hS_def
  -- Target: S.card ≤ m p - 1.
  -- Strategy: construct injection S → (univ : Finset (Fin (m p))).erase (c p),
  -- via k ↦ (gc.configs.get k) p. This map is injective by
  -- step_eq_of_moverAt_and_triple; image avoids c p by is_move.
  set T : Finset (Fin (sys.rs.m p)) :=
    ((Finset.univ : Finset (Fin (sys.rs.m p))).erase (c p))
    with hT_def
  have hT_card : T.card = sys.rs.m p - 1 := by
    rw [hT_def, Finset.card_erase_of_mem (Finset.mem_univ _)]; simp
  -- Define the map on S.
  have himg_mem : ∀ k ∈ S, (gc.configs.get k) p ∈ T := by
    intro k hk
    rw [hS_def, Finset.mem_filter] at hk
    obtain ⟨_, hmov, hlef, hmid, hrig⟩ := hk
    rw [hT_def, Finset.mem_erase]
    refine ⟨?_, Finset.mem_univ _⟩
    -- is_move at step k: v ≠ s, i.e. sys.f p L S R ≠ S; we derived
    -- sys.f p L S R = c p, so c p ≠ S = (gc.configs.get k) p.
    intro heq
    have hpriv : privileged sys (gc.configs.get k) p := by
      rw [← hmov]; exact gc.moverAt_privileged k
    -- privileged : sys.f p (c_k(left p)) (c_k p) (c_k(right p)) ≠ c_k p
    -- We have hmid : sys.f p ... = c p, heq : c p = (gc.configs.get k) p.
    unfold privileged at hpriv
    apply hpriv
    rw [hmid]; exact heq.symm
  have hinj : Set.InjOn (fun k => (gc.configs.get k) p) (S : Set (Fin gc.configs.length)) := by
    intro k₁ hk₁ k₂ hk₂ heq
    rw [hS_def, Finset.mem_coe, Finset.mem_filter] at hk₁ hk₂
    obtain ⟨_, hmov₁, hlef₁, _, hrig₁⟩ := hk₁
    obtain ⟨_, hmov₂, hlef₂, _, hrig₂⟩ := hk₂
    -- Both k₁ and k₂ have moverAt = p and same triple at p ( = (c(left p), ?, c(right p)) )
    -- Also (gc.configs.get k₁) p = (gc.configs.get k₂) p by heq.
    -- Apply step_eq_of_moverAt_and_triple.
    have hmov_eq : gc.moverAt k₁ = gc.moverAt k₂ := hmov₁.trans hmov₂.symm
    -- We use step_eq_of_moverAt_and_triple gc k₂ k₁:
    -- k₁ = k₂ iff source triples equal at moverAt k₂.
    have hk2_mov : gc.moverAt k₂ = p := hmov₂
    -- Bring everything to moverAt k₂ = p.
    refine step_eq_of_moverAt_and_triple gc k₂ k₁ hmov_eq ?_ ?_ ?_
    · rw [hk2_mov, hlef₁, ← hlef₂]
    · rw [hk2_mov]; exact heq
    · rw [hk2_mov, hrig₁, ← hrig₂]
  calc S.card = (S.image (fun k => (gc.configs.get k) p)).card :=
        (Finset.card_image_of_injOn hinj).symm
    _ ≤ T.card := by
        apply Finset.card_le_card
        intro v hv
        rw [Finset.mem_image] at hv
        obtain ⟨k, hkS, rfl⟩ := hv
        exact himg_mem k hkS
    _ = sys.rs.m p - 1 := hT_card

/-- Double-count: `Σ_k β(targetTripleOfStep k) ≤ L · Σ_p (m p - 1)`. -/
private theorem sum_beta_target_stepMoveEntry_le
    (gc : GoodCycle sys) :
    ∑ k : Fin gc.configs.length,
        betaOfTarget gc (targetTripleOfStep gc k) ≤
      gc.configs.length * ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) := by
  classical
  have hnd : gc.configs.Nodup :=
    List.nodup_iff_injective_get.mpr (fun j₁ j₂ h => gc.distinct j₁ j₂ h)
  set C : Finset (Config sys.rs) := gc.configs.toFinset with hC_def
  have hC_card : C.card = gc.configs.length := by
    rw [hC_def]; exact List.toFinset_card_of_nodup hnd
  -- Rewrite β(target k) = Σ_c ∈ C, [c matches target k at moverAt k].
  have h_beta : ∀ k : Fin gc.configs.length,
      betaOfTarget gc (targetTripleOfStep gc k) =
        ∑ c ∈ C, (if configTripleAt c (gc.moverAt k) =
                     (targetTripleOfStep gc k).2 then 1 else 0 : ℕ) := by
    intro k
    unfold betaOfTarget
    -- `(targetTripleOfStep gc k).1 = gc.moverAt k` holds definitionally.
    -- Convert list-filter length to Finset-filter cardinality.
    have heq :
        C.filter (fun c => configTripleAt c (gc.moverAt k) =
                              (targetTripleOfStep gc k).2) =
          (gc.configs.filter
              (fun c => decide
                (configTripleAt c (targetTripleOfStep gc k).1 =
                  (targetTripleOfStep gc k).2))).toFinset := by
      ext a
      simp [hC_def, targetTripleOfStep]
    rw [show (gc.configs.filter (fun c =>
        configTripleAt c (targetTripleOfStep gc k).1 =
          (targetTripleOfStep gc k).2)).length =
        (C.filter (fun c => configTripleAt c (gc.moverAt k) =
                              (targetTripleOfStep gc k).2)).card from by
      rw [heq, List.toFinset_card_of_nodup (hnd.filter _)]]
    rw [Finset.card_filter]
  -- Swap Σ_k Σ_c, then group by position p.
  have h_swap :
      ∑ k : Fin gc.configs.length,
          betaOfTarget gc (targetTripleOfStep gc k) =
        ∑ c ∈ C, ∑ k : Fin gc.configs.length,
          (if configTripleAt c (gc.moverAt k) =
              (targetTripleOfStep gc k).2 then 1 else 0 : ℕ) := by
    rw [Finset.sum_congr rfl (fun k _ => h_beta k)]
    exact Finset.sum_comm
  rw [h_swap]
  -- For fixed c, inner sum = Σ_p #{k : mover k = p ∧ matches at target} ≤ Σ_p (m p - 1).
  have h_inner : ∀ c ∈ C,
      ∑ k : Fin gc.configs.length,
        (if configTripleAt c (gc.moverAt k) =
            (targetTripleOfStep gc k).2 then 1 else 0 : ℕ) ≤
      ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) := by
    intro c _
    -- Indicator is 1 iff moverAt k gives a triple match at position moverAt k.
    -- We directly bound by Σ_p (m_p - 1) via matching_steps_card_le.
    -- Split the sum Σ_k by grouping over p := moverAt k.
    -- Bound via an injection from the matching-step set to Σ_p (Fin m_p \ {c p}).
    -- Set of steps k where the indicator is 1 (c matches target triple at moverAt k).
    set Kset : Finset (Fin gc.configs.length) :=
      (Finset.univ : Finset (Fin gc.configs.length)).filter
        (fun k => configTripleAt c (gc.moverAt k) = (targetTripleOfStep gc k).2)
      with hKset_def
    -- Sum of indicators = Kset.card.
    have h_sum_card :
        ∑ k : Fin gc.configs.length,
            (if configTripleAt c (gc.moverAt k) =
                (targetTripleOfStep gc k).2 then 1 else 0 : ℕ) = Kset.card := by
      rw [hKset_def, Finset.card_filter]
    rw [h_sum_card]
    -- Split Kset over position p = moverAt k: card(Kset) ≤ Σ_p card(Kset_p)
    -- where Kset_p = matching_steps at p, and each card(Kset_p) ≤ m_p - 1.
    have h_split :
        Kset.card = ∑ p : Fin sys.rs.n,
            (Kset.filter (fun k => gc.moverAt k = p)).card := by
      -- card_eq_sum_card_fiberwise with f = moverAt.
      refine Finset.card_eq_sum_card_fiberwise
        (s := Kset)
        (f := fun k : Fin gc.configs.length => gc.moverAt k)
        (t := (Finset.univ : Finset (Fin sys.rs.n))) ?_
      intro k _
      exact Finset.mem_univ (gc.moverAt k)
    rw [h_split]
    apply Finset.sum_le_sum
    intro p _
    -- Show (Kset.filter (moverAt = p)).card ≤ m_p - 1.
    -- The filter is {k | matching condition ∧ moverAt k = p}; this equals
    -- the filter used in matching_steps_card_le.
    have hsubset :
        Kset.filter (fun k => gc.moverAt k = p) ⊆
          (Finset.univ : Finset (Fin gc.configs.length)).filter
            (fun k => gc.moverAt k = p ∧
                      (gc.configs.get k) (left p) = c (left p) ∧
                      sys.f p ((gc.configs.get k) (left p))
                            ((gc.configs.get k) p)
                            ((gc.configs.get k) (right p)) = c p ∧
                      (gc.configs.get k) (right p) = c (right p)) := by
      intro k hk
      simp only [hKset_def, Finset.mem_filter, Finset.mem_univ, true_and] at hk
      obtain ⟨hmatch, hmov⟩ := hk
      -- hmov : gc.moverAt k = p; substitute p by moverAt k everywhere.
      subst hmov
      -- hmatch : configTripleAt c (moverAt k) = (targetTripleOfStep gc k).2
      simp only [configTripleAt, targetTripleOfStep, Prod.mk.injEq] at hmatch
      obtain ⟨h1, h2, h3⟩ := hmatch
      simp only [Finset.mem_filter, Finset.mem_univ, and_self, eq_self_iff_true,
                 true_and]
      -- After simp, `moverAt k = moverAt k` (rfl) has been absorbed; remaining
      -- is a 3-conjunct.
      refine And.intro ?_ (And.intro ?_ ?_)
      · exact h1.symm
      · exact h2.symm
      · exact h3.symm
    calc (Kset.filter (fun k => gc.moverAt k = p)).card
        ≤ ((Finset.univ : Finset (Fin gc.configs.length)).filter
            (fun k => gc.moverAt k = p ∧
                      (gc.configs.get k) (left p) = c (left p) ∧
                      sys.f p ((gc.configs.get k) (left p))
                            ((gc.configs.get k) p)
                            ((gc.configs.get k) (right p)) = c p ∧
                      (gc.configs.get k) (right p) = c (right p))).card :=
          Finset.card_le_card hsubset
      _ ≤ sys.rs.m p - 1 := matching_steps_card_le gc c p
  calc ∑ c ∈ C, ∑ k : Fin gc.configs.length,
          (if configTripleAt c (gc.moverAt k) =
              (targetTripleOfStep gc k).2 then 1 else 0 : ℕ)
      ≤ ∑ _c ∈ C, ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) :=
          Finset.sum_le_sum h_inner
    _ = C.card * ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) := by
          rw [Finset.sum_const, smul_eq_mul]
    _ = gc.configs.length * ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) := by
          rw [hC_card]

/-! ### Slab size lower bound -/

/-- Slab size of any move entry is at least `2^(n-3)` when `n ≥ 4`. -/
private theorem slabSize_ge_pow (gc : GoodCycle sys)
    (hn : 4 ≤ sys.rs.n) (e : MoveEntry sys gc) :
    2 ^ (sys.rs.n - 3) ≤ e.slabSize := by
  classical
  -- slabSize is the product of m j over j outside {left i, i, right i}.
  -- That finset has cardinality n - 3 (three distinct elements), and each factor is ≥ 2.
  unfold MoveEntry.slabSize
  set F : Finset (Fin sys.rs.n) :=
    (Finset.univ : Finset (Fin sys.rs.n)).filter
      (fun j => j ≠ left e.i ∧ j ≠ e.i ∧ j ≠ right e.i)
    with hF_def
  -- Compute F.card.
  have hF_card : F.card = sys.rs.n - 3 := by
    rw [hF_def]
    have : (Finset.univ : Finset (Fin sys.rs.n)).filter
             (fun j => j ≠ left e.i ∧ j ≠ e.i ∧ j ≠ right e.i) =
           (Finset.univ : Finset (Fin sys.rs.n)) \
             ({left e.i, e.i, right e.i} : Finset (Fin sys.rs.n)) := by
      ext j
      simp [Finset.mem_sdiff, Finset.mem_insert, Finset.mem_singleton,
            and_assoc, and_comm, not_or]
    rw [this]
    -- {left i, i, right i}.card = 3 using distinctness. Inline the
    -- distinctness since right_ne_self_local / right_ne_left_local are
    -- `private` in GoodCycleBasics.lean.
    have hne_ri : (right e.i).val ≠ e.i.val := by
      simp only [right_val]
      have ha := e.i.isLt
      by_cases hp1 : e.i.val + 1 < sys.rs.n
      · rw [Nat.mod_eq_of_lt hp1]; omega
      · rw [show e.i.val + 1 = sys.rs.n from by omega, Nat.mod_self]; omega
    have hne_li : (left e.i).val ≠ e.i.val := by
      simp only [left_val]
      have ha := e.i.isLt
      by_cases h0 : e.i.val = 0
      · rw [h0, Nat.zero_add, Nat.mod_eq_of_lt (by omega : sys.rs.n - 1 < sys.rs.n)]
        omega
      · rw [show e.i.val + sys.rs.n - 1 = (e.i.val - 1) + sys.rs.n from by omega,
            Nat.add_mod_right, Nat.mod_eq_of_lt (by omega)]
        omega
    have hne_lr : (left e.i).val ≠ (right e.i).val := by
      simp only [left_val, right_val]
      have ha := e.i.isLt
      by_cases h0 : e.i.val = 0
      · rw [h0, Nat.zero_add]
        rw [Nat.mod_eq_of_lt (by omega : sys.rs.n - 1 < sys.rs.n)]
        rw [Nat.mod_eq_of_lt (by omega : 1 < sys.rs.n)]
        omega
      · by_cases hlast : e.i.val + 1 < sys.rs.n
        · rw [Nat.mod_eq_of_lt hlast]
          rw [show e.i.val + sys.rs.n - 1 = (e.i.val - 1) + sys.rs.n from by omega,
              Nat.add_mod_right, Nat.mod_eq_of_lt (by omega)]
          omega
        · have hwrap : e.i.val + 1 = sys.rs.n := by omega
          rw [hwrap, Nat.mod_self]
          rw [show e.i.val + sys.rs.n - 1 = (e.i.val - 1) + sys.rs.n from by omega,
              Nat.add_mod_right, Nat.mod_eq_of_lt (by omega)]
          omega
    have hne1 : left e.i ≠ e.i := fun h => hne_li (congrArg Fin.val h)
    have hne2 : left e.i ≠ right e.i := fun h => hne_lr (congrArg Fin.val h)
    have hne3 : e.i ≠ right e.i := fun h => hne_ri (congrArg Fin.val h.symm)
    have htriple_card : ({left e.i, e.i, right e.i} : Finset (Fin sys.rs.n)).card = 3 := by
      have hmem1 : left e.i ∉ (insert e.i ({right e.i} : Finset (Fin sys.rs.n))) := by
        simp [hne1, hne2]
      have hmem2 : e.i ∉ ({right e.i} : Finset (Fin sys.rs.n)) := by
        simp [hne3]
      show (insert (left e.i) (insert e.i ({right e.i} : Finset (Fin sys.rs.n)))).card = 3
      rw [Finset.card_insert_of_notMem hmem1,
          Finset.card_insert_of_notMem hmem2,
          Finset.card_singleton]
    have hsub : ({left e.i, e.i, right e.i} : Finset (Fin sys.rs.n)) ⊆ Finset.univ := by
      intro x _; exact Finset.mem_univ _
    rw [Finset.card_sdiff_of_subset hsub, Finset.card_univ, Fintype.card_fin,
        htriple_card]
  -- Each factor m j ≥ 2.
  have h_factor : ∀ j ∈ F, 2 ≤ sys.rs.m j := fun j _ => sys.rs.m_pos j
  calc 2 ^ (sys.rs.n - 3) = 2 ^ F.card := by rw [hF_card]
    _ = ∏ _j ∈ F, (2 : ℕ) := by rw [Finset.prod_const]
    _ ≤ ∏ j ∈ F, sys.rs.m j := Finset.prod_le_prod (fun _ _ => by omega) h_factor

/-! ### Arithmetic lemmas -/

/-- Product-sum bound in ℕ: for any `s : Finset α` and `d : α → ℕ`,
    `2 · ∏_{i ∈ s} (2 + d i) ≥ 2^(|s|+1) + 2^|s| · ∑_{i ∈ s} d i`. -/
private theorem two_mul_prod_ge {α : Type*} (s : Finset α) (d : α → ℕ) :
    2 ^ (s.card + 1) + 2 ^ s.card * ∑ i ∈ s, d i ≤
      2 * ∏ i ∈ s, (2 + d i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert j S hj ih =>
    rw [Finset.card_insert_of_notMem hj,
        Finset.sum_insert hj, Finset.prod_insert hj]
    -- Need: 2^(S.card + 2) + 2^(S.card + 1) * (d j + ∑_S d) ≤ 2 * ((2 + d j) * ∏_S (2 + d))
    -- IH: 2^(S.card + 1) + 2^S.card * ∑_S d ≤ 2 * ∏_S (2 + d)
    -- Multiply IH by (2 + d j):
    -- (2 + d j) * (2^(S.card + 1) + 2^S.card * ∑_S d) ≤ (2 + d j) * 2 * ∏_S (2 + d)
    have hIH : 2 ^ (S.card + 1) + 2 ^ S.card * ∑ i ∈ S, d i ≤
               2 * ∏ i ∈ S, (2 + d i) := ih
    have hmul : (2 + d j) * (2 ^ (S.card + 1) + 2 ^ S.card * ∑ i ∈ S, d i) ≤
                (2 + d j) * (2 * ∏ i ∈ S, (2 + d i)) :=
      Nat.mul_le_mul_left _ hIH
    have hpow1 : (2:ℕ) ^ (S.card + 1) = 2 * 2 ^ S.card := by
      rw [pow_succ]; ring
    have hpow2 : (2:ℕ) ^ (S.card + 2) = 2 * 2 ^ (S.card + 1) := by
      rw [pow_succ]; ring
    have expand :
        (2 + d j) * (2 ^ (S.card + 1) + 2 ^ S.card * ∑ i ∈ S, d i) =
          2 ^ (S.card + 2) + d j * 2 ^ (S.card + 1) +
            (2 ^ (S.card + 1) * ∑ i ∈ S, d i + d j * 2 ^ S.card * ∑ i ∈ S, d i) := by
      rw [hpow2, hpow1]; ring
    -- RHS we want ≤: 2^(S.card + 2) + 2^(S.card + 1) * (d j + ∑_S d)
    -- = 2^(S.card + 2) + 2^(S.card + 1) * d j + 2^(S.card + 1) * ∑_S d
    -- = 2^(S.card + 2) + 2 * d j * 2^S.card + 2 * 2^S.card * ∑_S d
    -- Bound: 2^(S.card + 2) + d j * 2^(S.card + 1) ≤ 2^(S.card + 2) + 2 * d j * 2^S.card
    -- which uses 2^(S.card + 1) = 2 * 2^S.card, equal.
    nlinarith [expand, hmul,
      Nat.zero_le (d j * 2 ^ S.card * ∑ i ∈ S, d i),
      Nat.zero_le (2 ^ S.card * ∑ i ∈ S, d i),
      pow_pos (show (0:ℕ) < 2 from by decide) S.card]

/-- Product lower bound: `∏ m ≥ 2^n + 2^(n-1) · (Σm - 2n)` when each
    `m_i ≥ 2`, for `n ≥ 1`. Stated without Nat.sub: equivalent form
    `2·∏m ≥ 2^(n+1) + 2^n · (Σm - 2n)` rearranged to avoid subtraction. -/
private theorem stateProduct_lower_bound (rs : RingSpec) :
    2 ^ (rs.n + 1) + 2 ^ rs.n * ∑ i : Fin rs.n, (rs.m i - 2) ≤
      2 * stateProduct rs := by
  unfold stateProduct
  have h := two_mul_prod_ge (Finset.univ : Finset (Fin rs.n))
    (fun i => rs.m i - 2)
  have hcard : (Finset.univ : Finset (Fin rs.n)).card = rs.n := by simp
  rw [hcard] at h
  convert h using 2
  apply Finset.prod_congr rfl
  intro i _
  have := rs.m_pos i
  omega

/-- Key arithmetic: `4·3^(n-2) + (n+1)·2^(n-1) ≤ 2^(2n-4)` for `n ≥ 8`.
    Proven by induction on `n` starting at 8. -/
private theorem key_pow_ineq (n : ℕ) (hn : 8 ≤ n) :
    4 * 3 ^ (n - 2) + (n + 1) * 2 ^ (n - 1) ≤ 2 ^ (2 * n - 4) := by
  induction n, hn using Nat.le_induction with
  | base => decide
  | succ m hm ih =>
    -- LHS(m+1) = 4·3^(m-1) + (m+2)·2^m
    --         = 12·3^(m-2) + 2·(m+2)·2^(m-1)
    -- 4·LHS(m) = 16·3^(m-2) + 4·(m+1)·2^(m-1)
    -- 4·LHS(m) - LHS(m+1) = 4·3^(m-2) + (4m+4 - 2m - 4)·2^(m-1)
    --                     = 4·3^(m-2) + 2m·2^(m-1) ≥ 0
    -- 4·RHS(m) = 4·2^(2m-4) = 2^(2m-2) = RHS(m+1)
    -- So LHS(m+1) ≤ 4·LHS(m) ≤ 4·RHS(m) = RHS(m+1).
    have h1 : m + 1 - 2 = (m - 2) + 1 := by omega
    have h2 : m + 1 - 1 = (m - 1) + 1 := by omega
    have h3 : 2 * (m + 1) - 4 = (2 * m - 4) + 2 := by omega
    rw [h1, h2, h3]
    rw [pow_succ (a := (3 : ℕ)) (n := m - 2)]
    rw [pow_succ (a := (2 : ℕ)) (n := m - 1)]
    rw [show (2 : ℕ) ^ (2 * m - 4 + 2) = 2 ^ (2 * m - 4) * 4 from by
      rw [pow_add]; ring]
    -- Goal: 4 * (3^(m-2) * 3) + (m+2) * (2^(m-1) * 2) ≤ 2^(2m-4) * 4
    -- From ih: 4·3^(m-2) + (m+1)·2^(m-1) ≤ 2^(2m-4)
    -- ⇒ 4·(4·3^(m-2) + (m+1)·2^(m-1)) ≤ 4·2^(2m-4)
    -- ⇒ 16·3^(m-2) + 4(m+1)·2^(m-1) ≤ 2^(2m-4)·4
    -- Goal LHS = 12·3^(m-2) + 2(m+2)·2^(m-1) = 12·3^(m-2) + (2m+4)·2^(m-1)
    -- 16·3^(m-2) + 4(m+1)·2^(m-1) - [12·3^(m-2) + (2m+4)·2^(m-1)]
    -- = 4·3^(m-2) + (4m+4 - 2m - 4)·2^(m-1) = 4·3^(m-2) + 2m·2^(m-1) ≥ 0.
    nlinarith [ih, Nat.zero_le (3 ^ (m - 2)), Nat.zero_le (2 ^ (m - 1)),
      pow_pos (show (0:ℕ) < 3 from by decide) (m - 2),
      pow_pos (show (0:ℕ) < 2 from by decide) (m - 1),
      pow_pos (show (0:ℕ) < 2 from by decide) (2 * m - 4)]

/-- Basic bound: `n + 1 ≤ 2^(n-3)` for `n ≥ 8`. -/
private theorem succ_le_pow_n_sub_three (n : ℕ) (hn : 8 ≤ n) :
    n + 1 ≤ 2 ^ (n - 3) := by
  induction n, hn using Nat.le_induction with
  | base => decide
  | succ m hm ih =>
    have h1 : m + 1 - 3 = (m - 3) + 1 := by omega
    rw [h1, pow_succ]
    have hpos : 0 < 2 ^ (m - 3) := pow_pos (by decide) _
    linarith

/-- Arithmetic lemma: under sub-threshold product at `n ≥ 8`,
    `Σ m_p < 2^(n-3) + n - 1`. -/
private theorem sigma_m_lt_of_subMn (rs : RingSpec) (hn : 8 ≤ rs.n)
    (hsub : stateProduct rs < 4 * 3 ^ (rs.n - 2)) :
    ∑ p : Fin rs.n, rs.m p < 2 ^ (rs.n - 3) + rs.n - 1 := by
  classical
  -- Introduce σ := Σ (m_p - 2) ≥ 0, so Σm = σ + 2n.
  set σ := ∑ i : Fin rs.n, (rs.m i - 2) with hσ_def
  have h_sum_split : ∑ p : Fin rs.n, rs.m p = σ + 2 * rs.n := by
    rw [hσ_def]
    have h1 : ∑ i : Fin rs.n, (rs.m i - 2) + ∑ _i : Fin rs.n, (2 : ℕ) =
           ∑ i : Fin rs.n, rs.m i := by
      rw [← Finset.sum_add_distrib]
      apply Finset.sum_congr rfl
      intro i _
      have := rs.m_pos i
      omega
    have h2 : ∑ _i : Fin rs.n, (2 : ℕ) = 2 * rs.n := by
      rw [Finset.sum_const, smul_eq_mul, Finset.card_univ, Fintype.card_fin,
          Nat.mul_comm]
    linarith
  -- Lower bound product: 2^(n+1) + 2^n · σ ≤ 2 · ∏ m
  have h_prod : 2 ^ (rs.n + 1) + 2 ^ rs.n * σ ≤ 2 * stateProduct rs := by
    rw [hσ_def]; exact stateProduct_lower_bound rs
  -- Combine with hsub: 2·∏m < 8·3^(n-2), so 2^(n+1) + 2^n·σ ≤ 8·3^(n-2) - 1
  have h_comb : 2 ^ (rs.n + 1) + 2 ^ rs.n * σ + 1 ≤ 2 * (4 * 3 ^ (rs.n - 2)) := by
    have : 2 * stateProduct rs < 2 * (4 * 3 ^ (rs.n - 2)) :=
      (Nat.mul_lt_mul_left (show 0 < 2 by decide)).mpr hsub
    omega
  -- Rearrange: 2^n · σ < 8·3^(n-2) - 2^(n+1) - 1 < 8·3^(n-2) - 2^(n+1)
  have h_bound_sigma : 2 ^ rs.n * σ ≤ 8 * 3 ^ (rs.n - 2) - 2 ^ (rs.n + 1) - 1 := by
    -- From h_comb, subtract 2^(n+1) + 1 both sides, well-defined if 8·3^(n-2) ≥ 2^(n+1) + 1
    -- which is true for n ≥ 2.
    omega
  -- Need Σm < 2^(n-3) + n - 1, i.e., σ + 2n < 2^(n-3) + n - 1, i.e., σ < 2^(n-3) - n - 1.
  -- Sufficient: 2^n · σ < 2^n · (2^(n-3) - n - 1) = 2^(2n-3) - n·2^n - 2^n.
  -- We have 2^n·σ ≤ 8·3^(n-2) - 2^(n+1) - 1.
  -- Need: 8·3^(n-2) - 2^(n+1) - 1 < 2^n · (2^(n-3) - n - 1)
  -- i.e., 8·3^(n-2) - 2^(n+1) ≤ 2^n · (2^(n-3) - n - 1)
  -- i.e., 8·3^(n-2) + 2^n·(n+1) ≤ 2^n · 2^(n-3) + 2^(n+1) = 2^(2n-3) + 2^(n+1)
  -- Hmm let me redo. We want σ + 2n < 2^(n-3) + n - 1, i.e., σ + n + 1 < 2^(n-3).
  -- Sufficient: σ ≤ 2^(n-3) - n - 2 (for strict <).
  -- 2^n · σ ≤ 2^n · (2^(n-3) - n - 2) = 2^(2n-3) - (n+2)·2^n
  -- Want this bound to be ≥ 8·3^(n-2) - 2^(n+1) - 1.
  -- i.e., 8·3^(n-2) - 2^(n+1) - 1 ≤ 2^(2n-3) - (n+2)·2^n
  -- i.e., 8·3^(n-2) + (n+2)·2^n ≤ 2^(2n-3) + 2^(n+1) + 1
  -- i.e., 8·3^(n-2) + (n+2)·2^n ≤ 2^(2n-3) + 2^(n+1) + 1

  -- Let's use key_pow_ineq directly. It gives:
  --   4·3^(n-2) + (n+1)·2^(n-1) ≤ 2^(2n-4)
  -- Multiply by 2: 8·3^(n-2) + (n+1)·2^n ≤ 2·2^(2n-4) = 2^(2n-3)
  -- So 8·3^(n-2) + (n+1)·2^n ≤ 2^(2n-3).

  have hkey := key_pow_ineq rs.n hn
  have hkey2 : 8 * 3 ^ (rs.n - 2) + (rs.n + 1) * 2 ^ rs.n ≤ 2 ^ (2 * rs.n - 3) := by
    have hpow_n : (2 : ℕ) ^ rs.n = 2 * 2 ^ (rs.n - 1) := by
      have hn' : rs.n = (rs.n - 1) + 1 := by omega
      conv_lhs => rw [hn']
      rw [pow_succ]; ring
    have hpow_2n : (2 : ℕ) ^ (2 * rs.n - 3) = 2 * 2 ^ (2 * rs.n - 4) := by
      have hn' : 2 * rs.n - 3 = (2 * rs.n - 4) + 1 := by omega
      conv_lhs => rw [hn']
      rw [pow_succ]; ring
    have h1 : (rs.n + 1) * 2 ^ rs.n = 2 * ((rs.n + 1) * 2 ^ (rs.n - 1)) := by
      rw [hpow_n]; ring
    have h2 : (8 : ℕ) * 3 ^ (rs.n - 2) = 2 * (4 * 3 ^ (rs.n - 2)) := by ring
    rw [h1, h2, hpow_2n]
    have := Nat.mul_le_mul_left 2 hkey
    linarith
  -- Now prove the target.
  -- Goal: σ + 2n < 2^(n-3) + n - 1
  -- Since n ≥ 8, 2^(n-3) ≥ n+1 (by succ_le_pow_n_sub_three), so 2^(n-3) + n - 1 ≥ 2n,
  -- and RHS - 2n = 2^(n-3) - n - 1.
  have hn3 : rs.n + 1 ≤ 2 ^ (rs.n - 3) := succ_le_pow_n_sub_three rs.n hn
  -- Show σ < 2^(n-3) - n - 1, i.e., σ + n + 1 < 2^(n-3)
  -- Multiplying by 2^n (positive), sufficient: σ * 2^n + (n+1) * 2^n < 2^(n-3) * 2^n = 2^(2n-3)
  -- Have: σ * 2^n ≤ 8·3^(n-2) - 2^(n+1) - 1 (from h_bound_sigma)
  -- Sum: σ · 2^n + (n+1) · 2^n ≤ (8·3^(n-2) - 2^(n+1) - 1) + (n+1)·2^n
  --                             = 8·3^(n-2) + (n+1)·2^n - 2^(n+1) - 1
  --                             ≤ 2^(2n-3) - 2^(n+1) - 1   (by hkey2)
  --                             < 2^(2n-3)                  ✓
  -- So σ · 2^n + (n+1) · 2^n < 2^(2n-3) = 2^n · 2^(n-3).
  -- Hence σ + n + 1 < 2^(n-3) (cancelling positive 2^n).
  have h_sum_mul : (σ + (rs.n + 1)) * 2 ^ rs.n < 2 ^ rs.n * 2 ^ (rs.n - 3) := by
    have : (σ + (rs.n + 1)) * 2 ^ rs.n =
            2 ^ rs.n * σ + (rs.n + 1) * 2 ^ rs.n := by ring
    rw [this]
    have : 2 ^ rs.n * 2 ^ (rs.n - 3) = 2 ^ (2 * rs.n - 3) := by
      rw [← pow_add]
      congr 1; omega
    rw [this]
    have hpow_pos : 0 < 2 ^ (rs.n + 1) := pow_pos (by decide) _
    omega
  have hpow_pos : 0 < 2 ^ rs.n := pow_pos (by decide) _
  have h_final : σ + (rs.n + 1) < 2 ^ (rs.n - 3) := by
    by_contra h
    push_neg at h
    have : 2 ^ rs.n * 2 ^ (rs.n - 3) ≤ (σ + (rs.n + 1)) * 2 ^ rs.n := by
      have := Nat.mul_le_mul_right (2 ^ rs.n) h
      linarith
    omega
  -- Assemble: Σm = σ + 2n < 2^(n-3) + n - 1
  rw [h_sum_split]
  omega

/-- **§6(b) aggregated**: for any good cycle on `n ≥ 8` at sub-threshold
    product, some move entry in its determined dictionary is unblocked —
    its `α + β` count is strictly less than its slab size. -/
theorem exists_unblocked_moveEntry
    (gc : GoodCycle sys) (hn : 8 ≤ sys.rs.n)
    (hsub : stateProduct sys.rs < 4 * 3 ^ (sys.rs.n - 2)) :
    ∃ e : MoveEntry sys gc, e.blocked < e.slabSize := by
  classical
  by_contra hall
  push_neg at hall
  -- hall : ∀ e, slabSize e ≤ blocked e
  have hall' : ∀ k : Fin gc.configs.length,
      (stepMoveEntry gc k).slabSize ≤ (stepMoveEntry gc k).blocked :=
    fun k => hall _
  -- Sum over k.
  have hL : 0 < gc.configs.length := gc.configs_length_pos
  have hn4 : 4 ≤ sys.rs.n := by omega
  -- Lower bound: Σ_k slabSize(step k) ≥ L · 2^(n-3)
  have hslab_lb : ∀ k : Fin gc.configs.length,
      2 ^ (sys.rs.n - 3) ≤ (stepMoveEntry gc k).slabSize :=
    fun k => slabSize_ge_pow gc hn4 _
  have hsum_slab :
      gc.configs.length * 2 ^ (sys.rs.n - 3) ≤
        ∑ k : Fin gc.configs.length, (stepMoveEntry gc k).slabSize := by
    calc gc.configs.length * 2 ^ (sys.rs.n - 3)
        = ∑ _k : Fin gc.configs.length, 2 ^ (sys.rs.n - 3) := by
            rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, smul_eq_mul]
      _ ≤ ∑ k : Fin gc.configs.length, (stepMoveEntry gc k).slabSize :=
          Finset.sum_le_sum (fun k _ => hslab_lb k)
  -- Upper bound: Σ_k blocked(step k) = Σ α + Σ β ≤ L + L · Σ(m_p - 1)
  have hsum_alpha :
      ∑ k : Fin gc.configs.length, (stepMoveEntry gc k).alpha =
        gc.configs.length := by
    simp_rw [alpha_stepMoveEntry_eq_one]
    rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, smul_eq_mul, Nat.mul_one]
  have hsum_beta :
      ∑ k : Fin gc.configs.length, (stepMoveEntry gc k).beta ≤
        gc.configs.length * ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) := by
    -- (stepMoveEntry gc k).beta = betaOfTarget gc (targetTripleOfStep gc k).
    have h_beta_eq : ∀ k, (stepMoveEntry gc k).beta =
        betaOfTarget gc (targetTripleOfStep gc k) := by
      intro k
      unfold MoveEntry.beta betaOfTarget
      simp [stepMoveEntry, targetTripleOfStep, configTripleAt]
    simp_rw [h_beta_eq]
    exact sum_beta_target_stepMoveEntry_le gc
  have hsum_blocked :
      ∑ k : Fin gc.configs.length, (stepMoveEntry gc k).blocked ≤
        gc.configs.length + gc.configs.length *
          ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) := by
    have := calc
      ∑ k : Fin gc.configs.length, (stepMoveEntry gc k).blocked
          = ∑ k : Fin gc.configs.length,
              ((stepMoveEntry gc k).alpha + (stepMoveEntry gc k).beta) := by
            refine Finset.sum_congr rfl (fun k _ => ?_)
            rfl
        _ = (∑ k : Fin gc.configs.length, (stepMoveEntry gc k).alpha) +
            (∑ k : Fin gc.configs.length, (stepMoveEntry gc k).beta) :=
          Finset.sum_add_distrib
    rw [this, hsum_alpha]
    exact Nat.add_le_add_left hsum_beta _
  -- Sum of hall':
  have hsum_all :
      ∑ k : Fin gc.configs.length, (stepMoveEntry gc k).slabSize ≤
        ∑ k : Fin gc.configs.length, (stepMoveEntry gc k).blocked :=
    Finset.sum_le_sum (fun k _ => hall' k)
  -- Chain: L · 2^(n-3) ≤ Σ slab ≤ Σ blocked ≤ L + L · Σ(m_p - 1)
  have hchain :
      gc.configs.length * 2 ^ (sys.rs.n - 3) ≤
        gc.configs.length + gc.configs.length *
          ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) :=
    le_trans hsum_slab (le_trans hsum_all hsum_blocked)
  -- Divide by L: 2^(n-3) ≤ 1 + Σ(m_p - 1)
  have hdiv : 2 ^ (sys.rs.n - 3) ≤ 1 + ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) := by
    have hchain' : gc.configs.length * 2 ^ (sys.rs.n - 3) ≤
             gc.configs.length * (1 + ∑ p : Fin sys.rs.n, (sys.rs.m p - 1)) := by
      have hrw :
          gc.configs.length + gc.configs.length *
            ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) =
          gc.configs.length * (1 + ∑ p : Fin sys.rs.n, (sys.rs.m p - 1)) := by
        ring
      rw [hrw] at hchain
      exact hchain
    exact Nat.le_of_mul_le_mul_left hchain' hL
  -- Translate Σ(m_p - 1) to Σm - n.
  have hsum_eq : ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) + sys.rs.n =
                 ∑ p : Fin sys.rs.n, sys.rs.m p := by
    have h1 : ∑ p : Fin sys.rs.n, (sys.rs.m p - 1) + ∑ _p : Fin sys.rs.n, (1 : ℕ) =
              ∑ p : Fin sys.rs.n, sys.rs.m p := by
      rw [← Finset.sum_add_distrib]
      apply Finset.sum_congr rfl
      intro p _
      have := sys.rs.m_pos p
      omega
    have h2 : ∑ _p : Fin sys.rs.n, (1 : ℕ) = sys.rs.n := by
      rw [Finset.sum_const, smul_eq_mul, Finset.card_univ, Fintype.card_fin, Nat.mul_one]
    linarith
  -- So 2^(n-3) + n ≤ 1 + Σm, i.e., Σm ≥ 2^(n-3) + n - 1.
  have hlower : 2 ^ (sys.rs.n - 3) + sys.rs.n - 1 ≤ ∑ p : Fin sys.rs.n, sys.rs.m p := by
    have hn_ge : 1 ≤ sys.rs.n := by omega
    -- 2^(n-3) ≤ 1 + Σ(m-1)
    -- Add n: 2^(n-3) + n ≤ 1 + Σ(m-1) + n = 1 + Σm
    -- So Σm ≥ 2^(n-3) + n - 1.
    have : 2 ^ (sys.rs.n - 3) + sys.rs.n ≤ 1 + ∑ p : Fin sys.rs.n, sys.rs.m p := by
      have h1 : 2 ^ (sys.rs.n - 3) + sys.rs.n ≤
                (1 + ∑ p : Fin sys.rs.n, (sys.rs.m p - 1)) + sys.rs.n :=
        Nat.add_le_add_right hdiv _
      linarith [hsum_eq]
    omega
  -- Contradict arithmetic lemma.
  have hupper := sigma_m_lt_of_subMn sys.rs hn hsub
  omega

end LeanMn.SK
