#!/usr/bin/env python3
"""Generate the updated Lean tables for SixTuple.lean.

Output:
1. sixTupleEdgeVals: correct 617 CΦ boundary edges
2. condensationRankVals: 324 entries, max 26
3. sccSubRankVals: 324 entries (non-zero at 245=2, 251=1)

Verification:
- For non-SCC edges: condensationRank drops
- For SCC edges 245→251, 251→239: sccSubRank drops
- Edge 239→245: proved analytically (TMidVal forces fc drop)
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'claude'))
from cup2_theorem import build_system
from collections import defaultdict, deque

n = 9; ms, fs = build_system(n); N = 1
for m in ms: N *= m

def idx_to_config(idx):
    c = []
    for m in reversed(ms):
        c.append(idx % m); idx //= m
    return tuple(reversed(c))
def config_to_idx(c):
    idx = 0
    for j in range(n): idx = idx * ms[j] + c[j]
    return idx
def move(c, pos):
    L = c[(pos-1)%n]; S = c[pos]; R = c[(pos+1)%n]
    c2 = list(c); c2[pos] = fs[pos](L, S, R); return tuple(c2)
def fc(c): return sum(1 for j in range(n) if c[j] != c[(j+1)%n])
def tp(c):
    e = sum(1 for j in range(2,n-2) if c[j]==2 and c[(j+1)%n] in (0,1))
    i21 = sum(1 for j in range(2,n-2) if c[j]==2 and c[(j+1)%n]==1)
    w = sum(j for j in range(2,n-2) if c[j]==2 and c[(j+1)%n] in (0,1))
    return (e, i21, w)
def boundary6(c): return ((((c[0]*3+c[1])*3+c[2])*3+c[n-3])*3+c[n-2])*2+c[n-1]

bad_set = set(); tp_adj = {}
for i in range(N):
    if fc(idx_to_config(i)) > 0: bad_set.add(i); tp_adj[i] = []
for i in bad_set:
    c = idx_to_config(i); t = tp(c)
    for p in range(n):
        c2 = move(c, p); j = config_to_idx(c2)
        if c2 != c and j in bad_set and tp(c2) == t: tp_adj[i].append(j)

phi_full = {i: fc(idx_to_config(i)) for i in bad_set}
tp_rev = {i: [] for i in bad_set}
for i in bad_set:
    for j in tp_adj[i]: tp_rev[j].append(i)
changed = True
while changed:
    changed = False
    for j in bad_set:
        for i in tp_rev[j]:
            if phi_full[j] > phi_full[i]: phi_full[i] = phi_full[j]; changed = True

future_fc = {i: fc(idx_to_config(i)) for i in bad_set}
all_adj = {i: [] for i in bad_set}
for i in bad_set:
    c = idx_to_config(i)
    for p in range(n):
        c2 = move(c, p); j = config_to_idx(c2)
        if c2 != c and j in bad_set: all_adj[i].append(j)
all_rev = {i: [] for i in bad_set}
for i in bad_set:
    for j in all_adj[i]: all_rev[j].append(i)
changed = True
while changed:
    changed = False
    for j in bad_set:
        for i in all_rev[j]:
            if future_fc[j] > future_fc[i]: future_fc[i] = future_fc[j]; changed = True

# 617 CΦ edges
cphi_edges = set()
for i in bad_set:
    for j in tp_adj[i]:
        if future_fc[j] == future_fc[i] and phi_full[j] == phi_full[i]:
            c, c2 = idx_to_config(i), idx_to_config(j)
            b1, b2 = boundary6(c), boundary6(c2)
            if b1 != b2: cphi_edges.add((b1, b2))

assert len(cphi_edges) == 617

# Condensation via Tarjan's
adj6 = defaultdict(set); nodes6 = set()
for a, b in cphi_edges: adj6[a].add(b); nodes6.add(a); nodes6.add(b)

idx_c = [0]; stk = []; ll = {}; ix = {}; ons = set()
scc_list = []; scc_id = {}
def sc(v):
    ix[v] = idx_c[0]; ll[v] = idx_c[0]; idx_c[0] += 1
    stk.append(v); ons.add(v)
    for w in adj6.get(v, set()):
        if w not in ix: sc(w); ll[v] = min(ll[v], ll[w])
        elif w in ons: ll[v] = min(ll[v], ix[w])
    if ll[v] == ix[v]:
        s = []
        while True:
            w = stk.pop(); ons.discard(w); s.append(w)
            if w == v: break
        scc_list.append(set(s))
        for w in s: scc_id[w] = len(scc_list) - 1

sys.setrecursionlimit(10000)
for v in nodes6:
    if v not in ix: sc(v)

# Condensation DAG rank
cond_adj = defaultdict(set)
for a in nodes6:
    for b in adj6[a]:
        sa, sb = scc_id[a], scc_id[b]
        if sa != sb: cond_adj[sa].add(sb)

cond_nodes = set(range(len(scc_list)))
out_deg = {c: len(cond_adj.get(c, set())) for c in cond_nodes}
sinks = [c for c in cond_nodes if out_deg.get(c, 0) == 0]
cond_rank = {c: 0 for c in sinks}
cond_radj = defaultdict(list)
for c in cond_nodes:
    for s in cond_adj.get(c, set()): cond_radj[s].append(c)
q = deque(sinks)
while q:
    s = q.popleft()
    for c in cond_radj.get(s, []):
        new_r = cond_rank[s] + 1
        if c not in cond_rank or new_r > cond_rank[c]:
            cond_rank[c] = new_r; q.append(c)

# Build rank arrays
condensation_rank_vals = [0] * 324
for v in nodes6:
    condensation_rank_vals[v] = cond_rank[scc_id[v]]
# Nodes not in any CΦ transition get rank 0

# SCC sub-rank: within SCC {239, 245, 251}
# Edges: 239→245 (fc_down, excluded), 245→251, 251→239
# DAG rank on {245→251→239}: 239=0, 251=1, 245=2
scc_sub_rank_vals = [0] * 324
scc_sub_rank_vals[245] = 2
scc_sub_rank_vals[251] = 1
# 239 stays 0

# Output Lean code
print("-- Generated by gen_lean_tables.py")
print("-- CΦ 6-tuple edges (617 edges), condensation rank (max 26), SCC sub-rank")
print()

# Edge list
sorted_edges = sorted(cphi_edges)
print(f"def sixTupleEdgeVals : List (Nat × Nat) :=")
print("  [", end="")
for i, (a, b) in enumerate(sorted_edges):
    if i > 0: print(", ", end="")
    if i % 10 == 0 and i > 0: print("\n   ", end="")
    print(f"({a}, {b})", end="")
print("]")

print(f"\ntheorem sixTupleEdgeVals_length : sixTupleEdgeVals.length = 617 := by native_decide")

# Condensation rank
max_cond = max(condensation_rank_vals)
print(f"\ndef condensationRankVals : List Nat :=")
print("  [", end="")
for i, v in enumerate(condensation_rank_vals):
    if i > 0: print(", ", end="")
    if i % 18 == 0 and i > 0: print("\n   ", end="")
    print(f"{v}", end="")
print("]")
print(f"\ntheorem condensationRankVals_length : condensationRankVals.length = 324 := by native_decide")

# SCC sub-rank
print(f"\ndef sccSubRankVals : List Nat :=")
print("  [", end="")
for i, v in enumerate(scc_sub_rank_vals):
    if i > 0: print(", ", end="")
    if i % 18 == 0 and i > 0: print("\n   ", end="")
    print(f"{v}", end="")
print("]")
print(f"\ntheorem sccSubRankVals_length : sccSubRankVals.length = 324 := by native_decide")

# Verification theorems
print(f"""
/-- For every non-SCC sixTupleEdge, condensation rank drops.
    For SCC edges 245→251 and 251→239, scc sub-rank drops.
    The only remaining edge is 239→245 (fc-dropping, proved analytically). -/
theorem sixTuple_edge_lex_decrease :
    ∀ (s t : Nat), sixTupleEdgeVals.contains (s, t) = true →
      (condensationRankVals.getD t 0 < condensationRankVals.getD s 0) ∨
      (condensationRankVals.getD t 0 = condensationRankVals.getD s 0 ∧
       sccSubRankVals.getD t 0 < sccSubRankVals.getD s 0) ∨
      (s = 239 ∧ t = 245) := by
  native_decide""")

# Verify computationally
print("\n-- Verification:")
violations = 0
for a, b in sorted_edges:
    cr_a = condensation_rank_vals[a]
    cr_b = condensation_rank_vals[b]
    ss_a = scc_sub_rank_vals[a]
    ss_b = scc_sub_rank_vals[b]
    if cr_b < cr_a:
        pass  # condensation drops
    elif cr_b == cr_a and ss_b < ss_a:
        pass  # scc sub-rank drops
    elif a == 239 and b == 245:
        pass  # SCC fc edge
    else:
        violations += 1
        print(f"-- VIOLATION: ({a}, {b}): cond=({cr_a},{cr_b}), scc=({ss_a},{ss_b})")

print(f"-- Violations: {violations}")
if violations == 0:
    print("-- ✓ All edges handled by 3-way disjunction")
