#!/usr/bin/env python3
"""
Generate a minimal encoded active-base Lean file `PhiFullN.lean`.

This is the feasibility/production template used for the per-n computational
active finite-base route.
"""

from pathlib import Path
import sys


def weights(n: int):
    ws = []
    cur = 2 * (3 ** (n - 2))
    ws.append(cur)
    for _ in range(1, n - 1):
        cur //= 3
        ws.append(cur)
    ws.append(1)
    return ws


def modulus(i: int, n: int):
    return 2 if i == 0 or i == n - 1 else 3


def product_size(n: int):
    return 4 * (3 ** (n - 2))


def encode_lines(n: int):
    ws = weights(n)
    terms = [
        f"(c (fin{n} {i} (by omega))).1 * {ws[i]}"
        for i in range(n)
    ]
    return " + ".join(terms)


def decode_match_line(i: int, n: int, w: int):
    m = modulus(i, n)
    return (
        f"    | ⟨{i}, _⟩ => "
        f"⟨(d {w} {m} (by omega)).1, by have := (d {w} {m} (by omega)).2; "
        f"simp [cup2Spec, cup2M]⟩"
    )


def deep_copy_pair_lines(n: int):
    parts = []
    for k in range(4, n - 3):
        parts.append(
            f"  (c (fin{n} {k} (by omega))).1 == (c (fin{n} {k - 1} (by omega))).1 ||"
        )
        parts.append(
            f"  (c (fin{n} {k} (by omega))).1 == (c (fin{n} {k + 1} (by omega))).1 ||"
        )
    if parts:
        parts[-1] = parts[-1].removesuffix(" ||")
    return "\n".join(parts)


def active_theorem_cases(n: int):
    lines = []
    for i in range(n):
        lines.append(
            f"private theorem ac{n}b{i} : ∀ s : Fin N{n}, "
            f"activeCheck{n} s.1 ⟨{i}, by omega⟩ = true := by native_decide"
        )
    return "\n".join(lines)


def wrapper_cases(n: int):
    pieces = [f"exact ac{n}b{i} s" for i in range(n)]
    joined = " | ".join(pieces)
    return (
        f"  intro s p\n"
        f"  fin_cases p <;> first | {joined}\n"
    )


def generate(n: int) -> str:
    ws = weights(n)
    decode_lines = "\n".join(decode_match_line(i, n, ws[i]) for i in range(n))
    return f'''/- 
  Convergence/PhiFull{n}.lean — Encoded active no-drop base check at n={n}

  Generated by `probes/gen_phi_active_base.py`.
-/
import LeanMn.Convergence.PhiFullTP
import LeanMn.Convergence.SixTuple

namespace LeanMn

private abbrev hn4_{n} : 4 ≤ {n} := by omega
private abbrev hn9_{n} : 9 ≤ {n} := by omega
private def N{n} : Nat := {product_size(n)}
private abbrev fin{n} (k : Nat) (h : k < {n}) : Fin (cup2Spec {n} hn4_{n}).n :=
  ⟨k, by show k < {n}; exact h⟩

private def encodeCfg{n} (c : Config (cup2Spec {n} hn4_{n})) : Nat :=
  {encode_lines(n)}

private def decodeCfg{n} (idx : Nat) : Config (cup2Spec {n} hn4_{n}) :=
  let d (w m : Nat) (hm : 0 < m) : Fin m := ⟨(idx / w) % m, Nat.mod_lt _ hm⟩
  fun i => match i with
{decode_lines}

private def fc{n} (idx : Nat) : Nat := cup2Fc {n} hn4_{n} (decodeCfg{n} idx)
private def fire{n} (idx : Nat) (p : Fin {n}) : Nat :=
  encodeCfg{n} (move (cup2System {n} hn4_{n}) (decodeCfg{n} idx) p)
private def priv{n} (idx : Nat) (p : Fin {n}) : Bool :=
  decide (privileged (cup2System {n} hn4_{n}) (decodeCfg{n} idx) p)
private def good{n} (idx : Nat) : Bool :=
  decide (decodeCfg{n} idx ∈ (cup2GoodCycle {n} hn4_{n}).configs)
private def tpPres{n} (idx : Nat) (p : Fin {n}) : Bool :=
  cup2TpInvariant {n} hn4_{n} (move (cup2System {n} hn4_{n}) (decodeCfg{n} idx) p) ==
    cup2TpInvariant {n} hn4_{n} (decodeCfg{n} idx)
private def hasDeepCopyPair{n} (idx : Nat) : Bool :=
  let c := decodeCfg{n} idx
{deep_copy_pair_lines(n)}

private def phiStep{n} (phi : Array Nat) : Array Nat :=
  Array.ofFn fun (v : Fin N{n}) =>
    let base := fc{n} v.1
    let maxSucc := Id.run do
      let mut best := 0
      for p in List.finRange {n} do
        if priv{n} v.1 p && !good{n} (fire{n} v.1 p) && tpPres{n} v.1 p then
          let sv := fire{n} v.1 p
          if sv < N{n} then
            let sphi := phi.getD sv 0
            if sphi > best then best := sphi
      return best
    if good{n} v.1 then 0 else Nat.max base maxSucc

private def phiIter{n} : Nat → Array Nat
  | 0 => Array.ofFn fun (v : Fin N{n}) => if good{n} v.1 then 0 else fc{n} v.1
  | k + 1 => phiStep{n} (phiIter{n} k)

def phiFull{n}Array : Array Nat := phiIter{n} {2*n}
private def phiFull{n} (idx : Nat) : Nat := phiFull{n}Array.getD idx 0

private def activeCheck{n} (src_idx : Nat) (p : Fin {n}) : Bool :=
  let dst_idx := fire{n} src_idx p
  if !(priv{n} src_idx p) then true else
  if good{n} src_idx || good{n} dst_idx then true else
  if (cup2BoundaryState {n} hn4_{n} hn9_{n} (decodeCfg{n} dst_idx)).1 ==
     (cup2BoundaryState {n} hn4_{n} hn9_{n} (decodeCfg{n} src_idx)).1 then true else
  if !(hasDeepCopyPair{n} dst_idx) then true else
  if !(phiFull{n} dst_idx == phiFull{n} src_idx) then true else
  if !(tpPres{n} src_idx p) then true else
  sixTupleEdge
    (cup2BoundaryState {n} hn4_{n} hn9_{n} (decodeCfg{n} dst_idx))
    (cup2BoundaryState {n} hn4_{n} hn9_{n} (decodeCfg{n} src_idx))

{active_theorem_cases(n)}

theorem active_base{n} :
    ∀ src_idx : Fin N{n}, ∀ p : Fin {n},
      activeCheck{n} src_idx.1 p = true := by
{wrapper_cases(n)}

end LeanMn
'''


def main():
    if len(sys.argv) != 3:
        print("usage: gen_phi_active_base.py <n> <outpath>")
        raise SystemExit(1)
    n = int(sys.argv[1])
    out = Path(sys.argv[2])
    out.write_text(generate(n))


if __name__ == "__main__":
    main()
