#!/usr/bin/env python3
"""Find the (q, v) generating the L-cycle in peel(N_1(C)).

If there's always a cycle of length L in peel, is it generated by a
specific (q, v) — i.e., do there exist q, v such that
{c_i[q ← v] : i ∈ Z/L} forms a cycle under forced NG-moves?

For each record:
  Find all (q, v) such that the sequence c_0[q←v], c_1[q←v], ..., c_{L-1}[q←v]
  exists in N_1 and consecutive pairs are connected by forced NG-moves.
"""
from itertools import product as iproduct
from collections import defaultdict, Counter
import time


def m_n_sharp(n):
    if 5 <= n <= 8:
        return 32 * 3 ** (n - 4)
    return 4 * 3 ** (n - 2)


def enumerate_multisets(n, max_product):
    out = []
    def rec(i, prefix, prod):
        if i == n:
            if prod < max_product:
                out.append(tuple(prefix))
            return
        for m in range(2, max_product + 1):
            new_prod = prod * m
            min_remaining = 2 ** (n - i - 1)
            if new_prod * min_remaining >= max_product:
                break
            prefix.append(m)
            rec(i + 1, prefix, new_prod)
            prefix.pop()
    rec(0, [], 1)
    return out


def enumerate_all_cycles(ms, n, L_max, time_budget, max_cycles):
    all_starts = list(iproduct(*[range(m) for m in ms]))
    found = []
    seen_cycles = set()
    t0 = time.time()
    def dfs(start, config, det, path, movers):
        if len(found) >= max_cycles or time.time() - t0 > time_budget:
            return
        if len(path) > 1 and config == start:
            if set(movers) != set(range(n)):
                return
            L = len(movers)
            norm = min(tuple(path[i:L] + path[:i]) for i in range(L))
            if norm not in seen_cycles:
                seen_cycles.add(norm)
                found.append((list(path[:L]), list(movers), dict(det)))
            return
        if len(path) >= L_max:
            return
        for p in range(n):
            Lp = config[(p - 1) % n]; Sp = config[p]; Rp = config[(p + 1) % n]
            km = (p, Lp, Sp, Rp)
            forced_out = det.get(km)
            for new_val in range(ms[p]):
                if new_val == Sp:
                    continue
                if forced_out is not None and forced_out != new_val:
                    continue
                new_det = dict(det)
                new_det[km] = new_val
                ok = True
                for i in range(n):
                    if i == p:
                        continue
                    Li = config[(i - 1) % n]; Si = config[i]; Ri = config[(i + 1) % n]
                    ki = (i, Li, Si, Ri)
                    if ki in new_det and new_det[ki] != Si:
                        ok = False; break
                    new_det[ki] = Si
                if not ok:
                    continue
                nc = list(config); nc[p] = new_val; nc = tuple(nc)
                if nc != start and nc in set(path):
                    continue
                dfs(start, nc, new_det, path + [nc], movers + [p])
    for start in all_starts:
        if len(found) >= max_cycles or time.time() - t0 > time_budget:
            break
        dfs(start, start, {}, [start], [])
    return found


def value_sets(cycle, n):
    V = [set() for _ in range(n)]
    for c in cycle:
        for i in range(n):
            V[i].add(c[i])
    return V


def analyze(ms, n, cycle, movers, det):
    L = len(movers)
    V = value_sets(cycle, n)
    cycle_set = set(cycle)
    move_entries = {(p, Lv, Sv, Rv): val
                    for (p, Lv, Sv, Rv), val in det.items() if val != Sv}

    # For each (q, v): check if rigid shadow cycle c_i[q←v] exists as L-cycle
    #   - all c_i[q←v] differ from c_i (v ≠ c_i[q] for all i)
    #   - all c_i[q←v] ∉ cycle
    #   - consecutive c_i[q←v] → c_{i+1}[q←v] via forced move (at some p_i, same value)
    valid_qv = []
    for q in range(n):
        for v in V[q]:
            # All cycle steps where v != c_i[q]
            # If v = c_i[q] for some i, that step has c_i[q←v] = c_i ∈ cycle (dead)
            # So we need v ≠ c_i[q] for ALL i.
            if any(v == c[q] for c in cycle): continue
            # All c_i[q←v]
            shadow = []
            for c in cycle:
                nc = list(c); nc[q] = v; nc = tuple(nc)
                shadow.append(nc)
            # All distinct? Not needed for cycle — just successive transitions.
            # All ∉ cycle (already true since v ∉ V_q'?  Wait v ∈ V_q and v ≠ c_i[q], but could coincide with c_j for j≠i).
            if any(s in cycle_set for s in shadow): continue
            # Now check transitions: shadow[i] -> shadow[i+1] via forced NG-move
            cycle_ok = True
            for i in range(L):
                c_s = shadow[i]
                c_s_next = shadow[(i + 1) % L]
                # Find firing position: where do c_s and c_s_next differ?
                diffs = [j for j in range(n) if c_s[j] != c_s_next[j]]
                if len(diffs) != 1:
                    cycle_ok = False; break
                p_fire = diffs[0]
                # Forced move at p_fire: det[p, L, S, R] = new
                ctx = (p_fire, c_s[(p_fire - 1) % n], c_s[p_fire], c_s[(p_fire + 1) % n])
                if ctx not in move_entries:
                    cycle_ok = False; break
                if move_entries[ctx] != c_s_next[p_fire]:
                    cycle_ok = False; break
            if cycle_ok:
                valid_qv.append((q, v))

    return {
        'n': n, 'ms': ms, 'L': L,
        'valid_qv_count': len(valid_qv),
        'valid_qv': valid_qv[:3],  # sample
        'has_any': len(valid_qv) > 0,
    }


def main():
    print("=" * 72, flush=True)
    print("Rigid shadow (q, v) existence probe", flush=True)
    print("=" * 72, flush=True)
    plan = [
        (5, 3, 40, 3.0, 16),
        (6, 8, 15, 3.0, 17),
        (7, 40, 8, 3.0, 17),
    ]
    all_records = []
    for n, stride, max_cycles, tb, L_max in plan:
        Mn = m_n_sharp(n)
        multisets = enumerate_multisets(n, Mn)
        sampled = multisets[::stride]
        print(f"\n=== n={n}  {len(sampled)} multisets ===", flush=True)
        t0 = time.time()
        count = 0
        for idx, ms in enumerate(sampled):
            cycles = enumerate_all_cycles(ms, n, L_max, tb, max_cycles)
            for cycle, movers, det in cycles:
                L = len(movers)
                if L < 2 * n + 2: continue
                r = analyze(ms, n, cycle, movers, det)
                all_records.append(r)
                count += 1
            if (idx + 1) % max(1, len(sampled) // 10) == 0 or idx == len(sampled) - 1:
                print(f"  [{idx+1}/{len(sampled)}]  {time.time()-t0:.0f}s  records={count}", flush=True)

    print(f"\n{'='*72}\nResults\n{'='*72}", flush=True)
    by_n = defaultdict(list)
    for r in all_records: by_n[r['n']].append(r)
    for n, recs in sorted(by_n.items()):
        if not recs: continue
        print(f"\n  n={n}  records={len(recs)}")
        has = sum(1 for r in recs if r['has_any'])
        print(f"    ∃ rigid shadow (q, v): {has}/{len(recs)} ({100*has/len(recs):.1f}%)")
        counts = [r['valid_qv_count'] for r in recs]
        print(f"    # valid (q, v) pairs: min={min(counts)} max={max(counts)} avg={sum(counts)/len(counts):.1f}")


if __name__ == "__main__":
    main()
